"""Tests generated by AI, reviewed by human — after version."""
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
from payment import calculate_total


def test_no_discount():
    result = calculate_total(100.00)
    assert result["discount"] == 0.0
    assert result["tax"] == 8.0
    assert result["total"] == 108.0


def test_discount_applied_before_tax():
    """Discount reduces the taxable amount; tax is on the discounted subtotal."""
    result = calculate_total(100.00, discount_pct=10)
    assert result["discount"] == 10.0
    assert result["tax"] == 7.2        # 8% of 90, not 8% of 100
    assert result["total"] == 97.2     # 90 + 7.20


def test_discount_not_double_applied():
    """The bug was applying the discount twice in the total calculation."""
    result = calculate_total(200.00, discount_pct=20)
    discounted = 200 * 0.80           # 160
    expected_tax = round(discounted * 0.08, 2)   # 12.80
    expected_total = round(discounted + expected_tax, 2)  # 172.80
    assert result["total"] == expected_total


def test_zero_subtotal():
    result = calculate_total(0.0, discount_pct=50)
    assert result["total"] == 0.0


def test_full_discount():
    result = calculate_total(50.0, discount_pct=100)
    assert result["discount"] == 50.0
    assert result["tax"] == 0.0
    assert result["total"] == 0.0
